### ISSUE TITLE
Copy and paste causes crash

### ISSUE THREAD

**Issue by thefoothing** [NeoforceControls/XNA#10]
For some reason when I copy and paste into a control it crashes.

**Comment by Cyral** [comment]
Can you provide any error messages? We have no idea what you mean exactly

If you get an error about STAThread Attribute, find the main method in your program and add this before it:

```
[STAThread]
static void Main(string[] args)
```

**Comment by thefoothing** [comment]
Yep

**Comment by thefoothing** [comment]
that works

**Comment by Grimston** [comment]
.net requires all applications to run in STA mode for clipboard access.

If you must run in MTA there is a work around available.

I have not seen any difference running STA.
