### ISSUE TITLE
Multi colum with listbox

### ISSUE THREAD

**Issue by PedroAlvesq** [NeoforceControls/XNA#11]
how i put my listbox with multi coluns

**Comment by Grimston** [comment]
ListBox is not a DataGrid,

If your interested in creating a DataGrid and making a pull request to bring it back into Neoforce go for it.

**Comment by lucid2310** [comment]
I was actually looking at doing a datagrid but I ended up using the stackpanel provided. It allows you to stack other controls vertically or horizontal.

**Comment by Grimston** [comment]
Was just thinking about that. All you need to do is stack Label's, TextBox's, Button's, ImageBox's. and that's it, nice and simple.... probably wont look as nice as a proper DataGrid but its something.

**Comment by PedroAlvesq** [comment]
i create some labels to do like columms

**Comment by PedroAlvesq** [comment]
how i put if have no item in listbox  select say you must select a item

**Comment by Grimston** [comment]
Here is an example method that checks a specified `ListBox` if nothing is selected

``` CSharp
public bool NoItemSelected(ListBox listbox)
{
   if(listbox.ItemIndex == -1)
   {
      return true;
   }
   return false;
}
```

The key part is `ItemIndex == -1` if its `-1` then no item is currently selected.

**Comment by Cyral** [comment]
You could also shorten that to:

```
public bool NoItemSelected(ListBox listbox)
{
   return listbox.ItemIndex == -1;
}
```

:)

**Comment by PedroAlvesq** [comment]
can be close
