### ISSUE TITLE
problem change state with connection with server

### ISSUE THREAD

**Issue by PedroAlvesq** [NeoforceControls/XNA#13]
when i change the stage with connection with server the connection with server fail 
the code  void btnApply_Click(object sender, Controls.EventArgs e)
        {

```
        string user = txusername.Text.Trim();
        string userPassword = txpassword.Text.Trim();


        if (txusername.Text.Trim().Equals(String.Empty) || txpassword.Text.Trim().Equals(String.Empty))
        {
            TomShane.Neoforce.Controls.MessageBox.Show(NeoManager, TomShane.Neoforce.Controls.MessageBox.MessageBoxType.ERROR, "Username Ou Password is empty", "");

        }
        else
        {
            String ola = Create(userPassword);
            System.Console.WriteLine(ola);
            //InputHandler.Flush();
```

   // StateManager.PushState(GameRef.StartMenuScreen);
    //  StateManager.PushState(GameRef.StartMenuScreen);  
       cliente.Login(user, ola, ProcessComplete);
public void ProcessComplete(Headers header, ErrorCodes Erro)
        {
            System.Diagnostics.Debug.Write(Erro);
            if (header != Headers.Login)
            {
                return;
            }

```
        if (Erro == ErrorCodes.Sucess)
        {

           StateManager.PushState(GameRef.StartMenuScreen);

        }
       else
        {

            string msg = "";
            switch (Erro)
            {
                case ErrorCodes.InvalidLogin:
                    System.Console.Write(Erro);
                    msg = "username \\Password is incorrect";
                          break;
                case ErrorCodes.Error:
                    msg = "Server Is Offline";
                    break;
            }
            TomShane.Neoforce.Controls.MessageBox.Show(NeoManager, TomShane.Neoforce.Controls.MessageBox.MessageBoxType.ERROR, "" + msg, "");


        }

    }
```

  protected override void LoadContent()
        {

```
        base.LoadContent();
```

//if comment this code work
// Code i put in comment
              NeoManager = new Manager(Game); 
            NeoManager.AutoCreateRenderTarget = true; 
            NeoManager.AutoUnfocus = true;
            NeoManager.Initialize();
            */
          InitRes();

```
    }
```

**Comment by Cyral** [comment]
Umm... What is the error? I have no clue what the issue is, you need to be more specific. If the "Server fails" then that is unrelated to Neoforce controls.

Also, for checking if username and password are empty, just do `string.IsNullOrWhitespace(txtUsername.Text)`

**Comment by PedroAlvesq** [comment]
the problem if i use the 
cliente.Login(user, ola, ProcessComplete);  apply_click and  StateManager.PushState(GameRef.StartMenuScreen); in ProcessComple 
and put the StartMenuScreen with this code work
protected override void LoadContent()
{

```
    base.LoadContent();
```

}
but if i put the protected override void LoadContent()
{

```
    base.LoadContent();
```

//if comment this code work
// Code i put in comment
NeoManager = new Manager(Game);
NeoManager.AutoCreateRenderTarget = true;
NeoManager.AutoUnfocus = true;
NeoManager.Initialize();
*/
    }
don´t work

**Comment by PedroAlvesq** [comment]
i create a repository to see my entire code

**Comment by lucid2310** [comment]
what doesnt work, what is the error your getting?

Very basics to initialize the manager:
1. In the constructor for your main game class place the following lines of code:
   
   ```
        _manager = new Manager(this, graphics, "Default");
       _manager.SkinDirectory = @"..\..\Skins\";
       _manager.AutoUnfocus = false;
   ```
2. in the "Initialize" method in your main game class place the following lines of code:
   
   ```
       _manager.Initialize();
   ```
3. In the "Update" method of your main game class place the following line of code:
   
   ```
       _manager.Update(gameTime);
   ```
4. In the "Draw" method of your main game class place the following lines of code:
   
     _manager.BeginDraw(gameTime);
   
   ```
           spriteBatch.Begin();
           ... Draw sprites and other crap here...
           spriteBatch.End();
   ```
   
     _manager.EndDraw();

**Comment by PedroAlvesq** [comment]
problem as be solve can be close

**Comment by PedroAlvesq** [comment]
sorry but the problem is not complety solvit
the neoforce control don´t like i use gamestat 
this is the error i have it
'TomShane.Neoforce.Central.exe' (CLR v4.0.30319: TomShane.Neoforce.Central.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TomShane.Neoforce.Central.exe' (CLR v4.0.30319: TomShane.Neoforce.Central.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_pt_b77a5c561934e089\System.Windows.Forms.resources.dll'. Module was built without symbols.
A first chance exception of type 'System.InvalidOperationException' occurred in System.Windows.Forms.dll
'TomShane.Neoforce.Central.exe' (CLR v4.0.30319: TomShane.Neoforce.Central.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_pt_b77a5c561934e089\mscorlib.resources.dll'. Module was built without symbols.
ERROSystem.InvalidOperationException: A operação entre threads não é válida: controlo 'GameForm' acedido a partir de um thread diferente do thread onde foi criado.
   em System.Windows.Forms.Control.get_Handle()
   em Microsoft.Xna.Framework.WindowsGameWindow.get_Handle()
   em TomShane.Neoforce.Controls.Manager..ctor(Game game, GraphicsDeviceManager graphics, String skin)
   em TomShane.Neoforce.Controls.Manager..ctor(Game game)
   em TomShane.Neoforce.Central.Code.server.LoadContent() em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\Central\Code\server.cs:line 61
   em Microsoft.Xna.Framework.DrawableGameComponent.Initialize()
   em XRpgLibrary.GameState.Initialize() em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\XRpgLibrary\GameState.cs:line 46
   em TomShane.Neoforce.Central.Code.server.Initialize() em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\Central\Code\server.cs:line 89
   em Microsoft.Xna.Framework.Game.GameComponentAdded(Object sender, GameComponentCollectionEventArgs e)
   em Microsoft.Xna.Framework.GameComponentCollection.OnComponentAdded(GameComponentCollectionEventArgs eventArgs)
   em Microsoft.Xna.Framework.GameComponentCollection.InsertItem(Int32 index, IGameComponent item)
   em System.Collections.ObjectModel.Collection`1.Add(T item)
   em XRpgLibrary.GameStateManager.AddState(GameState newState) em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\XRpgLibrary\GameStateManager.cs:line 81
   em XRpgLibrary.GameStateManager.PushState(GameState newState) em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\XRpgLibrary\GameStateManager.cs:line 74
   em TomShane.Neoforce.Central.Code.TitleScreen.ProcessComplete(Headers header, ErrorCodes Erro) em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\Central\Code\TitleScreen.cs:line 255
   em TomShane.Neoforce.Central.Code.LoginClient.process(Object o) em c:\Users\Pedro\Dropbox\GAMES\TomShane.Neoforce.Controls.XNA4\Neoforce\Source\Central\Code\LoginClient.cs:line 57
