### ISSUE TITLE
Characters selection

### ISSUE THREAD

**Issue by PedroAlvesq** [NeoforceControls/XNA#14]
to put my charecter selection like this 
![aion0054](https://cloud.githubusercontent.com/assets/7807748/3331581/3b8bd0ac-f7de-11e3-863b-3b0d86986443.jpg) 
i have to use a arraylist for the buttons and label name
i can´t make a question

**Comment by Grimston** [comment]
Im not sure what your trying to achieve. something similar to
(--Cleric--) <-Button
|--Name--| <-Label

You could use a StackPanel to stack them correctly

**Comment by PedroAlvesq** [comment]
how use the stackpanel i using groupbox

**Comment by lucid2310** [comment]
wow man the graphics look great

**Comment by Cyral** [comment]
@lucid2310 It's a picture from [Aion Online](http://na.aiononline.com/en/)

**Comment by PedroAlvesq** [comment]
thanks but is image i pick the net of aion online to show with exemple i want make my character selection 
that image is not from my game lol

**Comment by PedroAlvesq** [comment]
now how make my stackpanel looks like a image i post
i want create array of the label grouppanel and button
this is my code
  private Button[] btnFirst = null;
        private Label[] nome = null;
        private GroupPanel[] group=null; 
 group[1] = new GroupPanel(NeoManager);
            group[1].Init();
            group[1].Parent = group1;

```
        // group.Anchor = Anchors.Left | Anchors.Top | Anchors.Right;
        group[1].Top = 660;
        group[1].Left = pnlRes.Top + 60;
        group[1].Width = 100;
        NeoManager.Add(group[1]);
        btnFirst[1] = new Button(NeoManager);
        btnFirst[1].Init();
        btnFirst[1].Parent = group[1];
        btnFirst[1].Anchor = Anchors.Left | Anchors.Top | Anchors.Right;
        btnFirst[1].Top = 660;
        btnFirst[1].Left = pnlRes.Top + 60 ;
        btnFirst[1].Width = 100;
        btnFirst[1].Text = "";
        NeoManager.Add(btnFirst[1]);
        nome[1] = new Label(NeoManager);
        nome[1].Init();
        nome[1].Parent = group[1];
        nome[1].Anchor = Anchors.Left | Anchors.Top | Anchors.Right;
        nome[1].Top = 680;
        nome[1].Left = pnlRes.Top + 60;
        nome[1].Width = 100;
        nome[1].Height = 25;
        nome[1].Text = "PDS\n"+"24";
        nome[1].BackColor = new Color(1, 1, 60);
        NeoManager.Add(nome[1]);
```

i my program crash but not error

**Comment by PedroAlvesq** [comment]
i find a onther way to do the same thing it create manual the grouppanel,button and label
topic can be close
