### ISSUE TITLE
How to disable keyboard events for interface elements

### ISSUE THREAD

**Issue by kostasoft** [NeoforceControls/XNA#32]
Hello!
Tell me, please, how to disable the response of controls on the key press? The trackbar does not move so that the interface buttons are not pressed. My cursor keys are interrogated in the program to create animations. And they also move the interface elements at the same time.

**Comment by Grimston** [comment]
To disable input you just need to set `InputEnabled` to `false` on the `Manager` instance this will disable input across all controls.

```CSHARP
_manager.InputEnabled = false;
```
Which is probably not what you want, instead you would need to check if you have an active control or not and deal with it appropriately.
```CSHARP
if (_manager.FocusedControl == null)
{
    //Handle game input
}
```
This way NeoForce will continue to work as expected and your game will also work.
