### ISSUE TITLE
manager = new Manager(this, graphics, "Default", true); don't work

### ISSUE THREAD

**Issue by the-morpher** [NeoforceControls/XNA#4]
hello,
im realy happy to see the neoforce has been supported again, i think about converting my application to use this one it give more things.

so when i just want to make a test, i can't run my application cause this line crash :

manager = new Manager(this, graphics, "Default", true);

it say that the manager constructor doesn't take 4 arguments.
so i have to use it that way :

manager = new Manager(this, graphics, "Default");

but in the tutorial you said that :

/ Create an instance of manager using Default skin. We set the fourth parameter to true,
// so the instance of manager is registered as an XNA game component and methods
// like Initialize(), Update() and Draw() are called automatically in the game loop.
// If you set this parameter to false, you have to call Manager.Initialize(), 
// Manager.Update() and Manager.Draw() manually in their respective overriden methods
// of the game class.
// If you use two-parameter constructor, Default skin is used and manager is registered.
manager = new Manager(this, graphics, "Default", true);  

i think it's a usefull that 4th argument as i don't need to type manager.initialize() manager.update() ...
so does it work or not ?

"by taking support of neoforce you have done a good job, keep going"

**Comment by Grimston** [comment]
Hi the-morpher,

Firstly thanks, I found neoforce to be extremely useful.

The example used to work on the old 3.1 version.  I must remember to update that as it will not work correctly with xna 4

The reason for dropping support for that constructor is you will get whats sometime called the "purple flash of death".

Its actually the back buffer being displayed. 

You should actually call (typing on my phone so if I make a mistake dont hold that against me :p)

manager.BeginDraw(gameTime);
Graphics.Clear(Color.Black); //or another color
//your drawing code

manager.EndDraw();

That should avoid the purple flashes on ui updates.

-------- Original message --------

**Comment by the-morpher** [comment]
Thanx Grimston to answer me that fast,
ok, i'll keep implementing this;

i've posted another question as it's another issue i've found before.
